### ISSUE TITLE
JBossDemoCentral.org site broken

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/continuous-delivery-demo-app#1]
Think something in last commit broke the jbossdemocentral.org site, none of the demos are being listed....

**Comment by tqvarnst** [comment]
Checking  now.

**Comment by tqvarnst** [comment]
Fixed. Seems there was an issue with the CA cert on the machine causing and java.security.InvalidAlgorithmParameterException when opening an SSL connection to GitHub. My best guess is that they have done some maintenance on OpenShift and updated the CA certs, without restarting the gears. A simple restart solved the issue.

/ Thomas

**Comment by tqvarnst** [comment]
Ohh and it had nothing to do with continuous-delivery-demo-app. This was a openshift issue.
